version: '2.1'
services:
  web56:
    image: orangehrm/orangehrm-environment-images:dev-5.6-centos
    ports:
      - "9056:443"
      - "3000:3000"
    volumes:
      - ./html:/var/www/html
      - ./config/web56/php/php.ini:/etc/php.ini
      - ./config/web56/mysql-client:/etc/mysql
      - ./config/web56/apache2/sites-available:/etc/httpd/sites-available
      - ./config/web56/apache2/sites-enabled:/etc/httpd/sites-enabled
      - ./config/web56/apache2/cert:/etc/httpd/cert
      - ./config/web56/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./logs/apache_logs/web56:/var/log/httpd
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.56
    restart: always
    container_name: dev_web_56

  web71:
    image: orangehrm/orangehrm-environment-images:dev-7.1-centos
    ports:
      - "9071:443"
    volumes:
      - ./html:/var/www/html
      - ./config/web71/php/php.ini:/etc/php.ini
      - ./config/web71/mysql-client:/etc/mysql
      - ./config/web71/apache2/sites-available:/etc/httpd/sites-available
      - ./config/web71/apache2/sites-enabled:/etc/httpd/sites-enabled
      - ./config/web56/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./config/web71/apache2/cert:/etc/httpd/cert
      - ./logs/apache_logs/web71:/var/log/httpd
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    sysctls:
      - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.71
    restart: always
    container_name: dev_web_71

  web70:
      image: orangehrm/orangehrm-environment-images:dev-7.0-centos
      ports:
        - "9070:443"
        - "3001:3000"
      volumes:
        - ./html:/var/www/html
        - ./config/web70/php/php.ini:/etc/php.ini
        - ./config/web70/mysql-client:/etc/mysql
        - ./config/web70/apache2/sites-available:/etc/httpd/sites-available
        - ./config/web70/apache2/sites-enabled:/etc/httpd/sites-enabled
        - ./config/web56/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
        - ./config/web70/apache2/cert:/etc/httpd/cert
        - ./logs/apache_logs/web70:/var/log/httpd
        - /etc/localtime:/etc/localtime
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      privileged: true
      sysctls:
        - kernel.shmmax=67371264
      networks:
        ohrmdevnet:
          ipv4_address: 10.5.0.70
      restart: always
      container_name: dev_web_70

  db55:
    image: mysql:5.5
    expose:
      - "3306"
    volumes:
      - ./config/db55:/etc/mysql
      - ./logs/mysql_logs/db55:/var/log
      - /etc/localtime:/etc/localtime
      - mysql55:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.5
    restart: always
    container_name: dev_mysql_55

  db56:
    image: mysql:5.6
    expose:
    - "3306"
    volumes:
    - ./config/db56:/etc/mysql
    - ./logs/mysql_logs/db56:/var/log
    - /etc/localtime:/etc/localtime
    - mysql56:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.4
    restart: always
    container_name: dev_mysql_56

  db57:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ./config/db57:/etc/mysql
      - ./logs/mysql_logs/db57:/var/log
      - /etc/localtime:/etc/localtime
      - mysql57:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.6
    restart: always
    container_name: dev_mysql_57

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime

    ports:
      - "9092:80"
    environment:
      PMA_HOSTS: db55,db56,db57,db102
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.20
    restart: always
    container_name: dev_phpmyadmin

  db102:
    image: mariadb:10.2
    expose:
      - "3306"
    volumes:
      - ./config/db102:/etc/mysql
      - ./logs/mariadb_logs/db102:/var/log
      - /etc/localtime:/etc/localtime
      - mariadb102:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.7
    restart: always
    container_name: dev_mariadb_102

  web72:
    image: orangehrm/orangehrm-environment-images:dev-7.2-centos
    ports:
      - "9072:443"
    volumes:
      - ./html:/var/www/html
      - ./config/web72/php/php.ini:/etc/php.ini
      - ./config/web72/mysql-client:/etc/mysql
      - ./config/web72/apache2/sites-available:/etc/httpd/sites-available
      - ./config/web72/apache2/sites-enabled:/etc/httpd/sites-enabled
      - ./config/web72/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./config/web72/apache2/cert:/etc/httpd/cert
      - ./logs/apache_logs/web72:/var/log/httpd
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro  
    privileged: true
    sysctls:
      - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.72
    restart: always
    container_name: dev_web_72

  ubuntuweb71:
    image: orangehrm/orangehrm-environment-images:dev-7.1-ubuntu-18.04
    ports:
      - "9100:443"
    volumes:
      - ./html:/var/www/html
      - ./config/ubuntuweb71/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./config/ubuntuweb71/apache2/cert:/etc/apache2/cert
      - ./config/ubuntuweb71/apache2/conf.d/apache2.conf:/etc/apache2/apache2.conf
      - ./logs/apache_logs/ubuntuweb71:/var/log/apache2
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.100
    restart: always
    container_name: dev_ubuntu_web_71

  mailcatcher:
    image: dockage/mailcatcher:0.6.5
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.23
    restart: always
    container_name: dev_mailcatcher

volumes:
  mysql55:
  mysql56:
  mysql57:
  mariadb102:
  oracle11:

networks:
  ohrmdevnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
